# Modified from https://github.com/jdblischak/smk-simple-slurm/blob/main/extras/status-sacct.sh
executor: cluster-generic
configfile: parameters_config.yaml
cluster-generic-submit-cmd:
  mkdir -p logs/ &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}
    --output=logs/{rule}-{wildcards}-%j.out
    --time={resources.time}
    --constraint={resources.constraint}
    --gres={resources.gpus}
    --parsable
cluster-generic-cancel-cmd:
  scancel
cluster-generic-status-cmd:
  profile/status_sacct.sh
default-resources:
  - partition=hns,normal,dpetrov
  - mem_gb=4
  - time="1:00:00"
  - cpus_per_task=1
  - constraint='"CPU_MNF:AMD|CPU_MNF:INTEL"'
  - gpus='"gpu:0"'
rerun-triggers: mtime
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
use-singularity: True
singularity-args: " --nv"
