reference:
  location: "/scratch/users/jahemker/seasonal_inbred/D.melanogaster.fa"
  euchromatic: "/scratch/users/jahemker/seasonal_inbred/reference/dm6/bedfiles/euchromatic_regions.sorted.bed"
project:
  name: "longread_sv_test2"
  dir: "/scratch/users/jahemker/seasonal_inbred/longread_sv_calling_test"
strains:
  "/scratch/users/jahemker/seasonal_inbred/longread_sv_calling_test/strains.txt"
tools:
  "/scratch/users/jahemker/seasonal_inbred/longread_sv_calling_test/tools.txt"
variant_params:
  min_length: "50"
  min_mapq: "20"
  min_caller_support: "2"
singularity_images:
  longread_sv_calling: "/scratch/users/jahemker/singularity_images/longread_sv_calling.sif"
  pav: "/home/groups/dpetrov/jahemker/singularity_images/pav_latest.sif"
